//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiYonetimiProje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BilgiYönetimi : DbContext
    {
        public BilgiYönetimi()
            : base("name=BilgiYönetimi")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<KARGO> KARGO { get; set; }
        public virtual DbSet<KITAP> KITAP { get; set; }
        public virtual DbSet<KITAPSEVKIYATI> KITAPSEVKIYATI { get; set; }
        public virtual DbSet<KITAPTURLERI> KITAPTURLERI { get; set; }
        public virtual DbSet<PERSONEL> PERSONEL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<YAYINEVISUBELERI> YAYINEVISUBELERI { get; set; }
        public virtual DbSet<YAZARLAR> YAZARLAR { get; set; }
    }
}
