//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiYonetimiProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class KITAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KITAP()
        {
            this.KITAPSEVKIYATI = new HashSet<KITAPSEVKIYATI>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ISBN_NO { get; set; }
        public string KitapAdı { get; set; }
        public Nullable<System.DateTime> YayinTarihi { get; set; }
        public Nullable<int> SayfaSayisi { get; set; }
        public Nullable<int> KitapTuruID { get; set; }
        public Nullable<int> YazarID { get; set; }
        public string Çevirmen { get; set; }
        public string KİtapPDF { get; set; }
    
        public virtual KITAPTURLERI KITAPTURLERI { get; set; }
        public virtual YAZARLAR YAZARLAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KITAPSEVKIYATI> KITAPSEVKIYATI { get; set; }
    }
}
